# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c48c689be15c61ccb7ba651991c87aea3f306fdc793a5285da2f246202dc45f47a3ce1d683e21e96a9489303a19271186cbce7251bcca5810eabd39fd764869b

test:
  secret_key_base: cd2a14377b1fd6214f66b284f1f293a9b075f09d23ca6183e12cbdf3af14f1f058b331a575ac34f0dc0e6c1ecbaae0b1d427ee6d5e1494d5e4dfe36d6ce36d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
